config/routes.rb
Rails.application.routes.draw do
  passwordless_for :users , at: '/', as: :auth
  get '/sign_up', :to => "pages#sign_up", :as => :sign_up

  resources :categories
  resources :tallies
  resources :teams
  resources :memberships

  delete '/tallies/:id',  :to => "tallies#destroy", :as => :delete_tally
  # post '/tallies/:id', :to => "tallies#update", :as => :tally
  #
  post '/categories/:id/increment', :to => 'categories#increment', :as => :increment_category
  post '/categories/:id/decrement', :to => 'categories#decrement', :as => :decrement_category

  get '/teams/:id/invite', :to => 'teams#invite', :as => :invite_team
  post '/teams/:id/send',  :to => 'teams#send_invite', :as => :send_invite_team

  # get '/teams/:id/invite/:token', :to => 'teams#accept_invite', :as => :accept_invite_team
  post '/teams/:id/invite/:token', :to => 'teams#accept_invite', :as => :accept_invite_team


  get '/archived', :to => 'categories#archived', :as => :archived_categories
  post '/archive/:id', :to => 'categories#archive', :as => :archive_category
  post '/restore/:id', :to => 'categories#restore', :as => :restore_category


  root 'pages#home'
end

app/views/pages/home.html.erb
<div class="bg-white">
  <div data-controller="menu" class="relative overflow-hidden">
      <div class="bg-gray-900 pt-6">
        <nav class="relative mx-auto flex max-w-7xl items-center justify-between px-6" aria-label="Global">
          <div class="flex flex-1 items-center">
            <div class="flex w-full items-center justify-between md:w-auto">
              <a href="#">
                <span class="sr-only">Moonside Labs</span>
                <%= image_tag "tally_icon.svg", class: "h-8 w-auto sm:h-10" %>
              </a>
              <div class="-mr-2 flex items-center md:hidden">
                <button data-action="menu#show" type="button" class="focus-ring-inset inline-flex items-center justify-center rounded-md bg-gray-900 p-2 text-gray-400 hover:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-white" aria-expanded="false">
                  <span class="sr-only">Open main menu</span>
                  <!-- Heroicon name: outline/bars-3 -->
                  <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
                  </svg>
                </button>
              </div>
            </div>
            <div class="hidden space-x-8 md:ml-10 md:flex">
              <span class="text-base font-medium text-white hover:text-gray-300">TalliedIt</span>
            </div>
          </div>
          <div class="hidden md:flex md:items-center md:space-x-6">
            <%= link_to "Log in", auth.sign_in_path, class: "text-base font-medium text-white hover:text-gray-300" %>
            <%= link_to "Sign up", sign_up_path, class: "inline-flex items-center rounded-md border border-transparent bg-gray-600 px-4 py-2 text-base font-medium text-white hover:bg-gray-700" %>
          </div>
        </nav>
      </div>

      <div data-menu-target="main backdrop backdrop2 close"
           data-transition-enter="duration-150 ease-out"
           data-transition-enter-start="opacity-0 scale-95"
           data-transition-enter-end="opacity-100 scale-100"
           data-transition-leave="duration-100 ease-in"
           data-transition-leave-start="opacity-100 scale-100"
           data-transition-leave-end="opacity-0 scale-95"
           class="absolute inset-x-0 top-0 origin-top transform p-2 transition hidden">
        <div class="overflow-hidden rounded-lg bg-white shadow-md ring-1 ring-black ring-opacity-5">
          <div class="flex items-center justify-between px-5 pt-4">
            <div>
              <%= image_tag "tally_icon.svg", class: "h-8 w-auto" %>
            </div>
            <div class="-mr-2">
              <button data-action="menu#hide" type="button" class="inline-flex items-center justify-center rounded-md bg-white p-2 text-gray-400 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-cyan-600">
                <span class="sr-only">Close menu</span>
                <!-- Heroicon name: outline/x-mark -->
                <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
          </div>
          <div class="pt-5 pb-6">
            <div class="space-y-1 px-2">
              <span class="text-base font-medium text-white hover:text-gray-300">TalliedIt</span>
            </div>
            <div class="mt-6 px-5">
              <%= link_to "Sign up", sign_up_path, class: "block w-full rounded-md bg-gradient-to-r from-teal-500 to-cyan-600 py-3 px-4 text-center font-medium text-white shadow hover:from-teal-600 hover:to-cyan-700" %>
            </div>
            <div class="mt-6 px-5">
              <p class="text-center text-base font-medium text-gray-500"><%= link_to "Log in", auth.sign_in_path, class: "text-gray-900 hover:underline" %></p>
            </div>
          </div>
        </div>
      </div>
    </header>
    <main>
      <div class="bg-gray-900 pt-10 sm:pt-16 lg:overflow-hidden lg:pt-8 lg:pb-14">
        <div class="mx-auto max-w-7xl lg:px-8">
          <div class="lg:grid lg:grid-cols-2 lg:gap-8">
            <div class="mx-auto max-w-md px-6 sm:max-w-2xl sm:text-center lg:flex lg:items-center lg:px-0 lg:text-left">
              <div class="lg:py-24">
                <h1 class="mt-4 text-4xl font-bold tracking-tight text-white sm:mt-5 sm:text-6xl lg:mt-6 xl:text-6xl">
                  <span class="block">Track more.
                    <span class="block bg-gradient-to-r from-teal-200 to-cyan-400 bg-clip-text pb-3 text-transparent sm:pb-5">
                      Share in one place.
                    </span>
                  </span>
                </h1>
                <p class="mt-4 text-base text-gray-300 sm:text-xl lg:text-lg xl:text-xl">
                  <span class="text-white">TalliedIt</span> lets you keep count and share what&apos;s important on the go.
                </p>
                <div class="mt-10 sm:mt-12 flex text-center justify-center">
                  <%= link_to "Try TalliedIt for Free", sign_up_path , class: "block w-4/5 lg:w-3/5 rounded-md bg-gradient-to-r from-teal-500 to-cyan-600 py-3 px-4 font-medium text-white shadow hover:from-teal-600 hover:to-cyan-700 focus:outline-none focus:ring-2 focus:ring-cyan-400 focus:ring-offset-2 focus:ring-offset-gray-900" %>
                </div>
              </div>
            </div>
            <div class="mt-12 -mb-16 sm:-mb-48 lg:relative lg:m-0">
              <div class="mx-auto max-w-md px-6 sm:max-w-2xl lg:max-w-none lg:px-0">
                <!-- Illustration taken from Lucid Illustrations: https://lucid.pixsellz.io/ -->
                <img class="w-full lg:absolute lg:inset-y-0 lg:left-0 lg:h-full lg:w-auto lg:max-w-none" src="https://tailwindui.com/img/component-images/cloud-illustration-teal-cyan.svg" alt="">
              </div>
            </div>
          </div>
        </div>
      </div>

    </main>

    <footer class="bg-gray-50" aria-labelledby="footer-heading">
      <h2 id="footer-heading" class="sr-only">Footer</h2>
      <div class="mx-auto max-w-md px-6 pt-12 sm:max-w-7xl lg:px-8 lg:pt-16">
        <div class="xl:grid xl:grid-cols-3 xl:gap-8">
          <div class="space-y-8 xl:col-span-1">
              <%= image_tag "tally_icon.svg", class: "h-10" %>
            <p class="text-base text-gray-500">Mixing it up in the lab with apps and experiments </p>
            <div class="flex space-x-6">
              <a href="https://twitter.com/LewchBewch" class="text-gray-400 hover:text-gray-500">
                <span class="sr-only">Twitter</span>
                <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                  <path d="M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84" />
                </svg>
              </a>

              <a href="https://github.com/lcanal" class="text-gray-400 hover:text-gray-500">
                <span class="sr-only">GitHub</span>
                <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                  <path fill-rule="evenodd" d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" clip-rule="evenodd" />
                </svg>
              </a>

              <a href="https://luiscanales.io" class="text-gray-400 hover:text-gray-500">
                <span class="sr-only">Personal Site</span>
                <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                  <path fill-rule="evenodd" d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10c5.51 0 10-4.48 10-10S17.51 2 12 2zm6.605 4.61a8.502 8.502 0 011.93 5.314c-.281-.054-3.101-.629-5.943-.271-.065-.141-.12-.293-.184-.445a25.416 25.416 0 00-.564-1.236c3.145-1.28 4.577-3.124 4.761-3.362zM12 3.475c2.17 0 4.154.813 5.662 2.148-.152.216-1.443 1.941-4.48 3.08-1.399-2.57-2.95-4.675-3.189-5A8.687 8.687 0 0112 3.475zm-3.633.803a53.896 53.896 0 013.167 4.935c-3.992 1.063-7.517 1.04-7.896 1.04a8.581 8.581 0 014.729-5.975zM3.453 12.01v-.26c.37.01 4.512.065 8.775-1.215.25.477.477.965.694 1.453-.109.033-.228.065-.336.098-4.404 1.42-6.747 5.303-6.942 5.629a8.522 8.522 0 01-2.19-5.705zM12 20.547a8.482 8.482 0 01-5.239-1.8c.152-.315 1.888-3.656 6.703-5.337.022-.01.033-.01.054-.022a35.318 35.318 0 011.823 6.475 8.4 8.4 0 01-3.341.684zm4.761-1.465c-.086-.52-.542-3.015-1.659-6.084 2.679-.423 5.022.271 5.314.369a8.468 8.468 0 01-3.655 5.715z" clip-rule="evenodd" />
                </svg>
              </a>
            </div>
          </div>

        </div>
        <div class="mt-12 border-t border-gray-200 py-8">
          <p class="text-base text-gray-400 xl:text-center">&copy; 2023 Moonside Labs, Inc. All rights reserved.</p>
        </div>
      </div>
    </footer>
  </div>
</div>

app/views/pages/sign_up.html.erb
<div class="flex min-h-full flex-col justify-center py-12 sm:px-6 lg:px-8">
  <div class="sm:mx-auto sm:w-full sm:max-w-md">
    <%= image_tag "tally_icon.svg", class: "mx-auto h-12 w-auto" %>
    <h2 class="mt-6 text-center text-3xl font-bold tracking-tight text-gray-900">Sign up to use TalliedIt</h2>
  </div>

  <div class="mt-8 sm:mx-auto sm:w-full sm:max-w-md">
    <div class="bg-white py-8 px-4 shadow sm:rounded-lg sm:px-10">
      <%= form_with model: @session, url: send(Passwordless.mounted_as).sign_in_path, data: { turbo: 'false' } do |f| %>
        <div>
          <label for="email" class="block text-sm font-medium text-gray-700">Email address</label>
          <div class="mt-1">
            <% email_field_name = :"passwordless[#{@email_field}]" %>
            <%= text_field_tag email_field_name, params.fetch(email_field_name, nil), required: true, class: "block w-full appearance-none rounded-md border border-gray-300 px-3 py-2 placeholder-gray-400 shadow-sm focus:border-cyan-500 focus:outline-none focus:ring-cyan-500 sm:text-sm" %>
          </div>
        </div>



        <div>
          <%= f.submit "Continue with email", class: "flex w-full justify-center rounded-md border border-transparent bg-cyan-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-cyan-700 focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:ring-offset-2 mt-3" %>
          <!--          <button type="submit" class="flex w-full justify-center rounded-md border border-transparent bg-cyan-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-cyan-700 focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:ring-offset-2">Sign in</button>-->
        </div>
      <% end %>

    </div>
  </div>
</div>