config/routes.rb
Rails.application.routes.draw do
  passwordless_for :users , at: '/', as: :auth
  get '/sign_up', :to => "pages#sign_up", :as => :sign_up

  resources :categories
  resources :tallies
  resources :teams
  resources :memberships

  delete '/tallies/:id',  :to => "tallies#destroy", :as => :delete_tally
  # post '/tallies/:id', :to => "tallies#update", :as => :tally
  #
  post '/categories/:id/increment', :to => 'categories#increment', :as => :increment_category
  post '/categories/:id/decrement', :to => 'categories#decrement', :as => :decrement_category

  get '/teams/:id/invite', :to => 'teams#invite', :as => :invite_team
  post '/teams/:id/send',  :to => 'teams#send_invite', :as => :send_invite_team

  # get '/teams/:id/invite/:token', :to => 'teams#accept_invite', :as => :accept_invite_team
  post '/teams/:id/invite/:token', :to => 'teams#accept_invite', :as => :accept_invite_team


  get '/archived', :to => 'categories#archived', :as => :archived_categories
  post '/archive/:id', :to => 'categories#archive', :as => :archive_category
  post '/restore/:id', :to => 'categories#restore', :as => :restore_category


  root 'pages#home'
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tallies, :dependent => :destroy

  def last_updated_local
    updated_at + Time.zone_offset('PST')
  end

  def last_tally
    tally = tallies.last
    unless tally.nil?
      return "Last tally: #{tally.last_updated_formatted}"
    end
    "No tallies yet"
  end

  def team_name
    Team.find(team_id).name
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_user!
  before_action :set_category, only: %i[show edit update destroy increment decrement]

  # GET /categories or /categories.json
  def index
    @teams = current_user.active_teams
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  def archived
    @teams = current_user.active_teams
    @categories = Category.where(archived: true, team_id: @teams.map(&:id))
  end

  def archive
    @category = Category.find(params[:id])
    @category.archived = true
    @category.save

    respond_to do |format|
      format.html { redirect_to categories_path, notice: 'Category was successfully archived.', header: 'Successfully Archived' }
      format.json { render :show, status: :ok, location: categories_path }
    end

  end

  def restore
    @category = Category.find(params[:id])
    @category.archived = false
    @category.save

    respond_to do |format|
      format.html { redirect_to archived_categories_path, notice: 'Category was successfully restored.', header: 'Successfully Restored' }
      format.json { render :show, status: :ok, location: categories_path }
    end
  end
  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    @category.user_id = current_user.id

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: categories_path }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_path, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: categories_path }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def increment
    tally = Tally.new(category_id: @category.id)

    respond_to do |format|
      if tally.save
        format.html { redirect_to categories_path, notice: "Incremented '#{@category.name}'" }
        format.json { render :show, status: :ok, location: categories_path }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def decrement
    last_tally = @category.tallies.last
    respond_to do |format|
      if !last_tally.nil? and last_tally.destroy
        format.html { redirect_to categories_path, notice: "Decremented tally from '#{@category.name}'" }
        format.json { render :show, status: :ok, location: categories_path }
      else
        format.html { redirect_to categories_path, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end

  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.where(id: params[:id], team_id: current_user.team_ids).first
  end

    # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name,:description,:team_id)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<li id="<%= dom_id category %>">
    <div class="flex items-center px-4 py-4 sm:px-6">
      <div class="min-w-0 flex-1 sm:flex sm:items-center sm:justify-between">
        <div class="truncate">
          <div class="flex text-sm">
            <p class="truncate font-medium text-cyan-600"><%= link_to category.name, edit_category_path(category) %></p>
            <p class="ml-1 flex-shrink-0 font-normal text-gray-500">with <%= pluralize(category.tallies.count, "Tally") %></p>
          </div>
          <div class="mt-2 flex">
            <div class="flex items-center text-sm text-gray-500">
              <!-- Heroicon name: mini/calendar -->
              <svg class="mr-1.5 h-5 w-5 flex-shrink-0 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M5.75 2a.75.75 0 01.75.75V4h7V2.75a.75.75 0 011.5 0V4h.25A2.75 2.75 0 0118 6.75v8.5A2.75 2.75 0 0115.25 18H4.75A2.75 2.75 0 012 15.25v-8.5A2.75 2.75 0 014.75 4H5V2.75A.75.75 0 015.75 2zm-1 5.5c-.69 0-1.25.56-1.25 1.25v6.5c0 .69.56 1.25 1.25 1.25h10.5c.69 0 1.25-.56 1.25-1.25v-6.5c0-.69-.56-1.25-1.25-1.25H4.75z" clip-rule="evenodd" />
              </svg>
              <p>
                <time datetime="2020-01-07"><%= category.last_tally %></time>
              </p>
            </div>
          </div>
        </div>

        <div class="mt-4 flex-shrink-0 sm:mt-0 sm:ml-5">
          <div class="flex space-x-2 justify-between mt-7 lg:mt-0 lg:justify-end">
            <% unless category.archived? %>
            <div>
              <%= link_to increment_category_path(category), data: { turbo_method: :post }, class: "inline-flex mr-3 items-center rounded-full border border-transparent bg-cyan-600 p-2 text-white shadow-sm hover:bg-cyan-700 focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:ring-offset-2" do %>
                <!-- Heroicon name: mini/plus -->
                <svg class="h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                  <path d="M10.75 4.75a.75.75 0 00-1.5 0v4.5h-4.5a.75.75 0 000 1.5h4.5v4.5a.75.75 0 001.5 0v-4.5h4.5a.75.75 0 000-1.5h-4.5v-4.5z" />
                </svg>
                <%= link_to decrement_category_path(category), data: { turbo_method: :post },   class: "inline-flex mr-3 items-center rounded-full border border-transparent bg-slate-600 p-2 text-white shadow-sm hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-slate-500 focus:ring-offset-2" do %>
                  <!-- Heroicon name: mini/minus -->
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-5 h-5">
                    <path fill-rule="evenodd" d="M4 10a.75.75 0 01.75-.75h10.5a.75.75 0 010 1.5H4.75A.75.75 0 014 10z" clip-rule="evenodd" />
                  </svg>
                <% end %>
              <% end %>
            </div>
            <% end %>
            <%= link_to "Edit", edit_category_path(category), class: "inline-flex items-center rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-cyan-500 " %>
          </div>
        </div>
      </div>
    </div>
</li>

app/views/categories/_form.html.erb
<%= form_with(model: category, class: "contents") do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3 drop-shadow-2xl">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>
      <ul>
        <% category.errors.each do |error| %>
                <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="space-y-8 divide-y rounde divide-gray-200 sm:space-y-5 bg-white shadow-sm mt-5 rounded-md">
    <div class="sm:space-y-5 py-5 px-5">
      <div class="space-y-6 sm:space-y-5">
        <div class="sm:grid sm:grid-cols-3 sm:items-start sm:gap-4">
          <%= form.label :name, class: "block text-sm font-medium text-gray-700 sm:mt-px sm:pt-2" %>
          <div class="mt-1 sm:col-span-2 sm:mt-0">
            <%= form.text_field :name, class: "block w-full max-w-lg rounded-md border-gray-300 shadow-sm focus:border-cyan-500 focus:ring-cyan-500 sm:text-sm" %>
          </div>
        </div>
        <div class="sm:grid sm:grid-cols-3 sm:items-start sm:gap-4">
          <%= form.label :description, class: "block text-sm font-medium text-gray-700 sm:mt-px sm:pt-2" %>
          <div class="mt-1 sm:col-span-2 sm:mt-0">
            <%= form.text_area :description, class: "block w-full max-w-lg rounded-md border-gray-300 shadow-sm focus:border-cyan-500 focus:ring-cyan-500 sm:text-sm" %>
          </div>
        </div>
        <div class="sm:grid sm:grid-cols-3 sm:items-start sm:gap-4">
          <%= form.label :team, class: "block text-sm font-medium text-gray-700 sm:mt-px sm:pt-2" %>
          <div class="mt-1 sm:col-span-2 sm:mt-0">
            <%= form.collection_select :team_id, current_user.teams, :id, :name, {}, { class: "block w-full max-w-lg rounded-md border-gray-300 shadow-sm focus:border-cyan-500 focus:ring-cyan-500 sm:text-sm" } %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="flex justify-end mt-5">
    <%= form.submit "Save" , class: "ml-3 inline-flex justify-center rounded-md border border-transparent bg-cyan-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-cyan-700 focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:ring-offset-2" %>
    <%= link_to "Cancel", categories_path, class: "ml-3 rounded-md border border-gray-300 bg-white py-3 px-4 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:ring-offset-2" %>
  </div>

  <% unless @category.id.nil? %>
    <div class="px-4 sm:px-6 lg:px-8 mt-5 lg:mt-10">
      <div class="sm:flex sm:items-center">
        <div class="sm:flex-auto">
          <h1 class="text-xl font-semibold text-gray-900">Tallies</h1>
          <p class="mt-2 text-sm text-gray-700">A list of all the tallies associated with this category.</p>
        </div>

      </div>
      <div class="mt-8 flex flex-col">
        <div class="-my-2 -mx-4 sm:-mx-6 lg:-mx-8">
          <div class="inline-block min-w-full py-2 align-middle">
            <div class="shadow-sm ring-1 ring-black ring-opacity-5">
              <table class="min-w-full border-separate" style="border-spacing: 0">
                <thead class="bg-gray-50">
                <tr>
                  <th scope="col" class="sticky top-0 z-10 border-b border-gray-300 bg-gray-50 bg-opacity-75 py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 backdrop-blur backdrop-filter sm:pl-6 lg:pl-8">Updated</th>
                  <th scope="col" class="sticky top-0 z-10 hidden border-b border-gray-300 bg-gray-50 bg-opacity-75 px-3 py-3.5 text-left text-sm font-semibold text-gray-900 backdrop-blur backdrop-filter sm:table-cell">Notes</th>
<!--                  <th scope="col" class="sticky top-0 z-10 hidden border-b border-gray-300 bg-gray-50 bg-opacity-75 px-3 py-3.5 text-left text-sm font-semibold text-gray-900 backdrop-blur backdrop-filter lg:table-cell"></th>-->
<!--                  <th scope="col" class="sticky top-0 z-10 border-b border-gray-300 bg-gray-50 bg-opacity-75 px-3 py-3.5 text-left text-sm font-semibold text-gray-900 backdrop-blur backdrop-filter">Role</th>-->
                  <th scope="col" class="sticky top-0 z-10 border-b border-gray-300 bg-gray-50 bg-opacity-75 py-3.5 pr-4 pl-3 backdrop-blur backdrop-filter sm:pr-6 lg:pr-8">
                    <span class="sr-only">Edit</span>
                  </th>
                </tr>
                </thead>
                <tbody class="bg-white">
                <% @category.tallies.order(updated_at: :desc).limit(15).each do |tally| %>
                  <tr>
                    <td class="whitespace-nowrap border-b border-gray-200 py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6 lg:pl-8">
                      <%= link_to tally.last_updated_formatted, tally, class: "text-cyan-600 hover:text-cyan-900" %>
                    </td>
                    <td class="whitespace-nowrap border-b border-gray-200 px-3 py-4 text-sm text-gray-500 hidden sm:table-cell">
                      <%= tally.notes %>
                    </td>
<!--                    <td class="whitespace-nowrap border-b border-gray-200 px-3 py-4 text-sm text-gray-500 hidden lg:table-cell"></td>-->
                    <!--                <td class="whitespace-nowrap border-b border-gray-200 px-3 py-4 text-sm text-gray-500">Member</td>-->
                    <td class="relative whitespace-nowrap border-b border-gray-200 py-4 pr-4 pl-3 text-right text-sm font-medium sm:pr-6 lg:pr-8">
                      <%= link_to 'Delete', delete_tally_path(tally), data: { turbo_method: :delete }, class: "text-cyan-600 hover:text-cyan-900" %>
<!--                      <a href="#" class="text-cyan-600 hover:text-cyan-900">Edit<span class="sr-only">, <%#= tally.created_at %></span></a>-->
                    </td>
                  </tr>
                <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="mt-12 flex justify-end">
      <p class="mt-2 text-sm text-gray-500 block">
        <% if category.archived? %>
          <%= link_to "Restore Category", restore_category_path(category), data: { turbo_method: :post }, class: "ml-3 rounded-md border border-gray-300 bg-white py-3 px-4 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:ring-offset-2"%>
        <% else %>
          <%= link_to "Archive Category", archive_category_path(category), data: { turbo_method: :post }, class: "ml-3 rounded-md border border-gray-300 bg-white py-3 px-4 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:ring-offset-2"%>
        <% end %>

      </p>
    </div>
    <div class="flex justify-end mt-5">
      <p class="mt-2 text-sm text-gray-500 block">
        <%= link_to 'Delete Category', category_path(category), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this category?" }, class: "text-red-600 hover:text-red-900" %>
      </p>
    </div>

  <% end %>
<% end %>

app/views/categories/archived.html.erb
<% content_for :title  do %>
  <div class="flex justify-between align-middle text-base mb-5">
  <span class="text-4xl">
    Archives
  </span>
    <%= link_to 'New category', new_category_path, class: "rounded-lg py-3 px-5 bg-cyan-600 text-white block font-medium" %>
  </div>
<% end %>

<% @teams.each do |team| %>
  <div class="border-b border-gray-200 pb-5 mb-7">
    <h3 class="flex justify-between align-middle text-lg font-medium leading-6 text-gray-900">
      <div class="inline-block">
        <%= image_tag team.owner.gravatar_url, class: "h-12 w-12 rounded-full mr-5 inline"%>
        <%= team.name %>
      </div>

    </h3>
  </div>
  <!--  <h2 class="text-xl font-bold leading-7 text-gray-900 sm:truncate sm:text-3xl sm:tracking-tight mb-3"><%#= team.name %></h2>-->
  <div class="overflow-hidden bg-white shadow sm:rounded-md mb-10">
    <ul role="list" class="divide-y divide-gray-200">
      <%= render team.archived_categories %>
    </ul>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl truncate"><%= @category.name %></h1>
  <%= render "form", category: @category %>
</div>

app/views/categories/index.html.erb
<% content_for :title  do %>
<div class="flex justify-between align-middle text-base mb-5">
  <span class="text-4xl">
    Categories
  </span>
  <%= link_to 'New category', new_category_path, class: "rounded-lg py-3 px-5 bg-cyan-600 text-white block font-medium" %>
</div>
<% end %>

<% @teams.each do |team| %>
  <div class="border-b border-gray-200 pb-5 mb-7">
    <h3 class="flex justify-between align-middle text-lg font-medium leading-6 text-gray-900">
      <div class="inline-block">
        <%= image_tag team.owner.gravatar_url, class: "h-12 w-12 rounded-full mr-5 inline"%>
        <%= team.name %>
      </div>

    </h3>
  </div>
<!--  <h2 class="text-xl font-bold leading-7 text-gray-900 sm:truncate sm:text-3xl sm:tracking-tight mb-3"><%#= team.name %></h2>-->
  <div class="overflow-hidden bg-white shadow sm:rounded-md mb-10">
    <ul role="list" class="divide-y divide-gray-200">
        <%= render team.categories %>
    </ul>
  </div>
<% end %>

app/views/categories/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New Category</h1>
  <%= render "form", category: @category %>
</div>

app/views/categories/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @category %>

    <%= link_to 'Edit this category', edit_category_path(@category), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Delete this category', category_path(@category), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>

    <%= link_to 'Back to categories', categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>